apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: di-collector
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: di-collector }
  template:
    metadata:
      labels: { app: di-collector }
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: collector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: /readyz, port: 8080 }
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            periodSeconds: 10
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            - name: TENANT_TOKENS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: TENANT_TOKENS
          resources: {{- toYaml .Values.resources | nindent 12 }}
